### ISSUE TITLE
Implement nesting of locations

### ISSUE THREAD

**Issue by fwolfst** [ecovillage/cabler#16]
Locations could have parents and children, and kinds. (like an Area has two Building which has three rooms). In the philosophy of the current implementation, I would let the "kind" field totally up to the user (not define "Building" or "Room" beforehand - it could also be "Rack I" -> "Row 2" etc).

A multitude of ruby gems allow that (e.g. https://www.ruby-toolbox.com/categories/Active_Record_Nesting ). While `act_as_tree` is not very advanced regarding theoretical informatics engineering and everything but performant, it seems a good choice (old, stable, boring, just needs an additional column). Transition to a more "clever" solution will always be possible, and the number of relationships in real world scenarios will never become significant wrt performce, I think.

**Comment by fwolfst** [comment]
@TheRealSyler  Feel free to open a new branch for it and point me to any problems you encounter.

**Comment by fwolfst** [comment]
Also, it might make sense to show the parent location(s) in the device show view

    Switch N-1
    Location: Room B / Floor A / Building 1

or

    Switch N-2
    Location: Rack B in Rechtes Regal in Keller

Mayb in breadcrumb style: https://bulma.io/documentation/components/breadcrumb/

**Comment by fwolfst** [comment]
Pretty much done with https://github.com/ecovillage/cabler/commit/371646f6406a2bd8af33fde2ce7491f50c7d819a (besides putting the nesting info in more places, especially the graph). Do you fire up a pull request when you are confident?

**Comment by TheRealSyler** [comment]
after i add the breadcrumbs thing to location, which i will do later today or tomorrow.

**Comment by TheRealSyler** [comment]
i added the breadcrumbs navigation in 1e19dc205a747dc69c28c4182a1b3dcf671ebb7f
now we have the recursion problem, i don't think that im able to solve that on my own.

**Comment by fwolfst** [comment]
Yep, fair enough. Draft a PR and I'll take care of the merging and maybe loop-detection.

For the latter, I think I would do two things: 1) prevent loop in the "accumulator" (and there is a more rubyish-way to do that) 2) in creation or editing of locations, validate that the parent is not also a child. I can tackle that if you want.

**Comment by fwolfst** [comment]
> now we have the recursion problem, i don't think that im able to solve that on my own.

Kind of solved in
https://github.com/ecovillage/cabler/commit/3befd74790dcc2b56cea4af203160b897fb91787
https://github.com/ecovillage/cabler/commit/cb9bc432d601c15513142f41dcae414a020a9637
https://github.com/ecovillage/cabler/commit/74a0de03ba02ba5bc8c2d290a7e84b70d10a405c
https://github.com/ecovillage/cabler/commit/bc6fb57e68c886113fed1460991b5746106e6fb7

At least you cannot create loops with standard UI techniques anymore.
Here and there somewhat esoteric code, but I think its fine enough.
