### ISSUE TITLE
How to support Action Text without Webpacker?

### ISSUE THREAD

**Issue by sedubois** [ecovillage/cabler#46]
With [Webpacker replaced by Sprockets](https://github.com/ecovillage/cabler#sprockets--webpacker), how would you use Action Text? I'd be curious to know as I'm [facing the same question](https://discuss.rubyonrails.org/t/how-to-use-action-text-without-webpack/77520) in my own app!

**Comment by sedubois** [comment]
Okay, I think I've [answered](https://discuss.rubyonrails.org/t/how-to-use-action-text-without-webpack/77520) my own question.

**Comment by fwolfst** [comment]
Thanks for the follow-up! Had no time investigating.
